import type { IconChoice } from './types'

/**
 * The icon catalogue, offline. Every one-colour mark ships as an SVG file under
 * `public/icons/` (generated by `scripts/build-icons.mjs`), and `index.json` is the
 * search index over them. Ranking is the one the server used, so search behaves the same.
 */

type Entry = { s: string; t: string; h: string }

/** Colour logos and uploads are painted as authored; one-colour marks are masked and tinted. */
export const isColourLogo = (slug: string) => slug.startsWith('dash:') || slug.startsWith('data:')

/** Where the file sits in the extension. Absolute: the extension root is the page's root. */
export function iconHref(slug: string) {
  if (!slug) return ''
  if (slug.startsWith('data:')) return slug
  if (slug.startsWith('dash:')) return `/icons/dash/${encodeURIComponent(slug.slice(5))}.svg`
  if (slug.startsWith('lucide:')) return `/icons/lu/${encodeURIComponent(slug.slice(7))}.svg`
  return `/icons/si/${encodeURIComponent(slug)}.svg`
}

/**
 * A mark, inlined, so a tile never waits on the network to draw it.
 *
 * The problem this solves: a `mask-image` only starts loading once the tile carrying it
 * has been painted, so tiles always appeared complete with their text and the marks
 * dropped in a frame or two later. Preloading cannot fix it — a mask reads a cache that
 * neither `new Image()` nor `<link rel="preload" as="image">` fills, and warming it with a
 * real masked element works in Chrome but not in a Firefox extension page, where the
 * tiles simply fetched everything again. See the gotcha in CLAUDE.md.
 *
 * So the mark stops being a network resource. Each one is fetched once, turned into a
 * `data:` URI and kept in `localStorage`; from the next new tab onwards the URI is read
 * synchronously at first render and the mask needs no request at all. A miss just falls
 * back to the file path, which is exactly the old behaviour — this can never be slower
 * than not having it.
 */
const CACHE = 'vp_icons'

/**
 * Percent-encoded, not base64: no `btoa` UTF-8 trap, and it survives CSS `url("…")`.
 *
 * The guard has to allow what comes before the tag — every lucide mark opens with its
 * ISC licence comment, and requiring `<svg` first silently refused all of them. It still
 * refuses an HTML error page, which is the thing worth keeping out of the cache.
 */
const SVG_OPENER = /^\s*(?:<\?xml[^>]*\?>|<!--[\s\S]*?-->|<!DOCTYPE[^>]*>)*\s*<svg/i

export function svgToDataUri(text: string): string {
  if (!SVG_OPENER.test(text)) throw new Error('not an svg')
  return `data:image/svg+xml,${encodeURIComponent(text)}`
}

type IconCache = { v: string; m: Record<string, string> }

const readCache = (): Record<string, string> => {
  try {
    const raw = JSON.parse(localStorage.getItem(CACHE) ?? 'null') as IconCache | null
    // Tied to the build: a new version may ship redrawn marks, and a stale inline copy
    // would outlive the file it came from.
    return raw && raw.v === __APP_VERSION__ ? raw.m : {}
  } catch {
    return {} // private mode, disabled storage, or junk in the key
  }
}

let inlined = readCache()

/** The URL a mask should use: the inlined copy when there is one, the file otherwise. */
export const iconUrl = (slug: string) => inlined[slug] ?? iconHref(slug)

/**
 * Fill the cache for the marks a hub uses. Fire-and-forget on purpose — nothing waits for
 * it, so a cold first run paints exactly as it does today and only the next tab is faster.
 * The map is rewritten to just these slugs, so dropping a link prunes its mark too.
 */
export async function cacheIcons(slugs: Iterable<string>): Promise<void> {
  const wanted = [...new Set(slugs)].filter((slug) => slug && !isColourLogo(slug))
  const next: Record<string, string> = {}
  await Promise.all(
    wanted.map(async (slug) => {
      if (inlined[slug]) {
        next[slug] = inlined[slug]
        return
      }
      try {
        const response = await fetch(iconHref(slug))
        if (response.ok) next[slug] = svgToDataUri(await response.text())
      } catch {
        // A missing or unreadable mark just stays a file path forever. Not worth a retry.
      }
    }),
  )
  inlined = next
  try {
    localStorage.setItem(CACHE, JSON.stringify({ v: __APP_VERSION__, m: next } satisfies IconCache))
  } catch {
    // Over quota or storage disabled: the page still works, it just re-fetches next time.
  }
}

/**
 * What the picker offers before anyone types. Search covers the whole catalogue; this is
 * the browsable shortlist, so it spans the stack first and then everything else a portal
 * tends to link to. Slugs missing from the bundle are dropped silently.
 */
const SUGGESTED_SLUGS = [
  // infrastructure and orchestration
  'kubernetes', 'docker', 'podman', 'redhatopenshift', 'rancher', 'helm', 'terraform',
  'ansible', 'vagrant', 'proxmox', 'vmware', 'openstack', 'portainer', 'traefikproxy',
  'nginx', 'apache', 'caddy', 'istio', 'linkerd', 'consul', 'vault',
  // data
  'mongodb', 'postgresql', 'mysql', 'mariadb', 'sqlite', 'redis', 'elasticsearch',
  'opensearch', 'clickhouse', 'influxdb', 'neo4j', 'apachecassandra', 'apachekafka',
  'rabbitmq', 'apacheairflow', 'apachespark', 'snowflake', 'databricks', 'dbeaver',
  // observability
  'grafana', 'prometheus', 'kibana', 'logstash', 'sentry', 'datadog', 'newrelic',
  'splunk', 'pagerduty', 'opsgenie', 'uptimekuma', 'lucide:activity',
  // storage and files
  'minio', 'nextcloud', 'owncloud', 'dropbox', 'googledrive', 'synology', 'truenas',
  // ci/cd and code
  'github', 'gitlab', 'gitea', 'bitbucket', 'git', 'jenkins', 'circleci', 'travisci',
  'argo', 'sonarqubeserver', 'jfrog', 'npm', 'yarn', 'pnpm',
  // languages and frameworks
  'nodedotjs', 'python', 'go', 'rust', 'typescript', 'javascript', 'php', 'ruby',
  'openjdk', 'dotnet', 'react', 'vuedotjs', 'angular', 'svelte', 'nextdotjs', 'vite',
  'tailwindcss', 'graphql', 'swagger', 'postman', 'insomnia',
  // clouds and hosting
  'cloudflare', 'digitalocean', 'heroku', 'vercel', 'netlify', 'firebase',
  'supabase', 'hetzner', 'lucide:cloud-cog',
  // security and access
  'keycloak', 'auth0', 'okta', 'bitwarden', '1password', 'keepassxc', 'wireguard',
  'openvpn', 'tailscale', 'letsencrypt', 'pfsense', 'opnsense',
  // work and communication
  'slack', 'discord', 'telegram', 'whatsapp', 'signal', 'zoom', 'googlemeet',
  'gmail', 'jira', 'confluence', 'notion', 'obsidian', 'trello',
  'asana', 'linear', 'clickup', 'zendesk', 'intercom',
  // design and media
  'figma', 'canva', 'blender', 'youtube', 'spotify', 'twitch',
  'netflix', 'plex', 'jellyfin', 'obsstudio', 'vlcmediaplayer',
  // hardware and home
  'raspberrypi', 'arduino', 'homeassistant', 'nvidia', 'intel', 'amd', 'apple',
  'linux', 'ubuntu', 'debian', 'archlinux', 'fedora', 'alpinelinux', 'lucide:monitor',
  // browsers and the wider web
  'googlechrome', 'firefox', 'brave', 'duckduckgo', 'wikipedia', 'stackoverflow',
  'reddit', 'medium', 'steam', 'lucide:linkedin',
  // money
  'stripe', 'paypal', 'visa', 'mastercard', 'bitcoin', 'ethereum', 'coinbase',
  // generic shapes for anything without a brand
  'lucide:server', 'lucide:database', 'lucide:cloud', 'lucide:archive', 'lucide:folder',
  'lucide:file-text', 'lucide:book-open', 'lucide:activity', 'lucide:shield', 'lucide:key',
  'lucide:terminal', 'lucide:globe', 'lucide:link', 'lucide:gauge', 'lucide:bell',
  'lucide:wrench', 'lucide:hard-drive', 'lucide:network', 'lucide:lock', 'lucide:mail',
  'lucide:calendar', 'lucide:users', 'lucide:user', 'lucide:building', 'lucide:map-pin',
  'lucide:search', 'lucide:settings', 'lucide:chart-line', 'lucide:chart-pie', 'lucide:clock',
  'lucide:camera', 'lucide:music', 'lucide:video', 'lucide:image', 'lucide:printer',
  'lucide:cpu', 'lucide:wifi', 'lucide:radio', 'lucide:zap', 'lucide:flame',
  'lucide:heart', 'lucide:star', 'lucide:bookmark', 'lucide:flag', 'lucide:tag',
  'lucide:package', 'lucide:truck', 'lucide:plane', 'lucide:car', 'lucide:home',
  'lucide:coffee', 'lucide:shopping-cart', 'lucide:credit-card', 'lucide:wallet',
  'lucide:graduation-cap', 'lucide:briefcase', 'lucide:life-buoy', 'lucide:message-square',
  'lucide:phone', 'lucide:send', 'lucide:inbox', 'lucide:cloud-download', 'lucide:recycle',
  'lucide:leaf', 'lucide:sun', 'lucide:moon', 'lucide:umbrella', 'lucide:thermometer',]

/** What people type vs what the icon is actually called. simple-icons carries no Amazon
 *  or AWS marks, so `s3` and friends have no brand icon to find — point them at a
 *  sensible generic instead and let the URL field cover the rest. */
const ALIASES: Record<string, string | string[]> = {
  k8s: 'kubernetes',
  es: 'elasticsearch',
  elk: 'elasticsearch',
  pg: 'postgresql',
  postgres: 'postgresql',
  gh: 'github',
  dockerhub: 'docker',
  // Marks simple-icons doesn't carry: the colour logo from dashboard-icons first, a
  // generic as fallback so the query still resolves before the dash index has loaded.
  s3: ['dash:aws', 'lucide:archive'],
  aws: ['dash:aws', 'lucide:cloud'],
  amazon: ['dash:aws', 'lucide:cloud'],
  ec2: ['dash:aws', 'lucide:server'],
  lambda: ['dash:aws', 'lucide:zap'],
  azure: ['dash:azure', 'lucide:cloud'],
  gcp: ['dash:google-cloud', 'lucide:cloud'],
  bucket: 'lucide:archive',
  vm: 'lucide:server',
  haproxy: ['dash:haproxy', 'lucide:network'],
  zabbix: ['dash:zabbix', 'lucide:activity'],
  nagios: ['dash:nagios', 'lucide:activity'],
  oracle: ['dash:oracle', 'lucide:database'],
  ibm: ['dash:ibm', 'lucide:building'],
  linode: ['dash:linode', 'lucide:cloud'],
  nexus: ['dash:nexus', 'lucide:package'],
  windows: ['dash:microsoft-windows', 'lucide:monitor'],
  teams: ['dash:microsoft-teams', 'lucide:message-square'],
  microsoftteams: ['dash:microsoft-teams', 'lucide:message-square'],
  argocd: ['dash:argo-cd', 'argo'],
  mssql: ['dash:microsoft-sql-server', 'lucide:database'],
  sqlserver: ['dash:microsoft-sql-server', 'lucide:database'],
  memcached: 'lucide:database',
  zookeeper: 'lucide:network',
  monday: 'lucide:calendar',
  mondaydotcom: 'lucide:calendar',
  photoshop: 'lucide:image',
  adobephotoshop: 'lucide:image',
  linkedin: ['dash:linkedin', 'lucide:linkedin'],
  sonarqube: 'sonarqubeserver',}

let index: Entry[] | null = null
let bySlug = new Map<string, Entry>()

/** ~250KB, fetched the first time the picker opens — never on the browse path. */
async function catalogue() {
  if (index) return index
  const loaded = (await fetch('/icons/index.json').then((response) => response.json())) as Entry[]
  bySlug = new Map(loaded.map((entry) => [entry.s, entry]))
  index = loaded
  return loaded
}

const toChoice = (entry: Entry): IconChoice => ({ slug: entry.s, title: entry.t, hex: entry.h })

export async function searchIcons(query: string): Promise<IconChoice[]> {
  const all = await catalogue()
  const needle = query.trim().toLowerCase()
  // An alphabetical dump opens on 3M and 4chan, which helps nobody running a stack.
  if (!needle) {
    return [...new Set(SUGGESTED_SLUGS)]
      .map((slug) => bySlug.get(slug))
      .filter((entry): entry is Entry => Boolean(entry))
      .map(toChoice)
  }

  // An alias pointing at a logo this build does not carry is simply not a match.
  const aliased = [ALIASES[needle] ?? []].flat().filter((slug) => bySlug.has(slug))
  const scored: { entry: Entry; rank: number }[] = []
  for (const entry of all) {
    const title = entry.t.toLowerCase()
    const rank =
      aliased.includes(entry.s) ? -1
      : title === needle ? 0
      : title.startsWith(needle) ? 1
      : title.includes(needle) ? 2
      : entry.s.includes(needle) ? 3
      : 99
    if (rank < 99) scored.push({ entry, rank })
  }
  // Equal rank: the full-colour logo goes first — it is the one people mean.
  const colour = (item: { entry: Entry }) => (item.entry.s.startsWith('dash:') ? 0 : 1)
  scored.sort(
    (a, b) => a.rank - b.rank || colour(a) - colour(b) || a.entry.t.length - b.entry.t.length,
  )
  return scored.slice(0, 120).map((item) => toChoice(item.entry))
}
